// import localFont from "next/font/local";
import { ClerkProvider, SignedOut } from "@clerk/nextjs";
import "./globals.css";
import { dark } from "@clerk/themes";
import { ptBR } from "@clerk/localizations";
import { Lato } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({ weight: ["300", "400", "700"], subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      className
      localization={ptBR}
      appearance={{
        baseTheme: dark,
        variables: {
          fontSize: "16px",
        },
      }}
    >
      <html lang="en">
        <body>
          <SignedOut></SignedOut>
          <main className={lato.className}>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
